### ISSUE TITLE
Using another postcss plugin as a wrapper - problem migrating from v7 to v8

### ISSUE THREAD

**Issue by garygreen** [postcss/postcss#1566] opened 2021-04-24 23:32 UTC
We have a problem migrating from v7 to v8 it seems our workflow is no longer supported with the new way of defining plugins.

It doesn't seem possible to programmatically call existing postcss plugins using your own wrapper. Our use case is that we want to define config settings asynchronously at runtime, then wrap an existing postcss plugin and use it with that config.

### Use to work in Postcss 7:

```js
async function getConfigForThirdPartyPlugin()
{
    // Perform some async function here and return an object of some config options
}

function myPlugin() {
	return postcss.plugin('postcss-my-plugin-wrapper', function (opts) {
		return function (root, result) {
			return getConfigForThirdPartyPlugin().then(function(opts) {
				return require('postcss-some-third-party-plugin')(opts)(root, result);
			});
		};
	});
}

module.exports = myPlugin;
```

### What we have tried for Postcss 8:

```js
function myPlugin() {
	return {
		postcssPlugin: 'postcss-my-plugin-wrapper',
		prepare: function (result) {
			return getConfigForThirdPartyPlugin().then(function(opts) {
				return require('postcss-some-third-party-plugin')(opts)(root, result);
			});
		}
	};
}

module.exports = myPlugin;
```

The above errors with "(node:2832) UnhandledPromiseRejectionWarning: TypeError: require(...)(...) is not a function" because `postcss-some-third-party-plugin` is on v8 and returns a plugin instance itself, with `{ postcssPlugin: '...', OnceExit }` etc.

Is there a way we can migrate our existing v7 plugin to v8 so that it supports asynchronously setting up some config options at runtime and allowing it to wrap an existing third party plugin and pass that config on?

**Comment by ai** [comment] 2021-04-25 00:39
Do you need to support PostCSS 7? Why do you have `require` in `myPlugin`?

**Comment by garygreen** [comment] 2021-04-25 00:50
@ai We don't need PostCSS 7 support - we're trying to upgrade but we're not sure how to support this use case. It's possible we're misunderstanding how `prepare` is supposed to be used. We use `require` in `myPlugin` to initialise the third party plugin we're trying to use...

**Comment by ai** [comment] 2021-04-25 00:53
`prepare` should return PostCSS 8 plugin event handlers.

Also, you need to set a `myPlugin.postcss = true` flag that it is PostCSS plugin.

```js
function myPlugin() {
	return {
		postcssPlugin: 'postcss-my-plugin-wrapper',
		prepare: function (result) {
			return getConfigForThirdPartyPlugin().then(function(opts) {
				return {
					OnceExit (root) {
						…
					},
					…
				}
			});
		}
	};
}

myPlugin.postcss = true

module.exports = myPlugin;
```

**Comment by garygreen** [comment] 2021-04-25 01:07
Thanks for the information much appreciated. So it looks like the main issue is that `prepare` doesnt support async. How would you suggest we wrap our plugin around another and being able to programmatically and asynchronously pass options to it?

**Comment by garygreen** [comment] 2021-04-25 01:08
As I understand v7 was fully async in how it defined plugins

**Comment by ai** [comment] 2021-04-25 01:23
> How would you suggest we wrap our plugin around another and being able to programmatically and asynchronously pass options to it?

Tell me what is your plugin doing. Why do you need to `require` another plugin?

**Comment by ai** [comment] 2021-04-25 01:24
One of the ways is to move config loading from `prepare` to plugin’s events
https://github.com/postcss/postcss-mixins/blob/main/index.js#L180

**Comment by garygreen** [comment] 2021-04-25 02:07
The problem with that approach is we can't technically move the loading of the config to the third party plugin... we want to pass the options to it but the options should be built asynchronously. It's a tricky one

**Comment by ai** [comment] 2021-04-25 02:12
Maybe you should change that third-party plugin or ask about some additional API.

I am closing this issue since it is a question, not a bug report.

**Closed by ai** 2021-04-25 02:12 UTC

**Comment by garygreen** [comment] 2021-04-25 14:41
@ai it's my understanding that all of the other processors `Once, AtRule` etc support async functions? If so, how come `prepare` doesn't? This means we don't have an easy upgrade path from v7 to v8... sounds like a bug to me.

**Comment by ai** [comment] 2021-04-25 14:46
>  it's my understanding that all of the other processors Once, AtRule etc support async functions?

Yes

> If so, how come prepare doesn't?

Because PostCSS call it in a different context and it was hard to add async there.

You can help me with PR if you want to add async support to `prepare`.
