### ISSUE TITLE
Nested css rules with postcss 8

### ISSUE THREAD

**Issue by JulienKode** [postcss/postcss#1611] opened 2021-07-01 12:39 UTC
With @leozero

By upgrading postcss 7 to postcss 8 we encounter an issue.

On certain version of postcss the AST see some css with 1 selector, and with other version it is see as two selector.

The issues is available here:
https://github.com/JulienKode/postcss-8-issue
- https://github.com/JulienKode/postcss-8-issue/blob/master/dist/index.prefixed.css
- https://github.com/JulienKode/postcss-8-issue/blob/chore/working-version-postcss-8/dist/index.prefixed.css

We have two branch:
- old postcss 8 version that are working well
- new postcss 8 version that have the issue 

Here is a good example of the issue, the following css:
```css
.foo {
  svg {
    display: none;
  }

  .bar {
    display: inline;
  }
}
```

Will have this output in postcss `8.0.9`
```css 
.stuff .foo svg {
    display: none;
  }
.stuff .foo .bar {
   display: inline;
}
```

But in postcss `8.1.0` this produce this output:
```css
.stuff .foo .stuff svg {
    display: none;
  }
.stuff .foo .stuff .bar {
   display: inline;
}
```

Did you have any idea what is causing this issue and how we can resolve it ? 
For now we keep old postcss 8 version

**Comment by ai** [comment] 2021-07-01 13:18
Can you update all dependencies to the latest version and update deep subdependencies by calling `nom update` or `yarn upgrade`

**Comment by JulienKode** [comment] 2021-07-01 16:13
Thanks for your reply and your help @ai, after upgrading we still have the issue

**Comment by ai** [comment] 2021-07-01 16:14
Can you simplify reproduction repo by cleaning PostCSS plugins? For instance, `postcss-import` and `tailwindcss`.

**Comment by JulienKode** [comment] 2021-07-01 16:18
Thanks for your quick reply.

Here is the issue cleaned https://github.com/JulienKode/postcss-8-issue/pull/new/issue/cleaned

**Comment by JulienKode** [comment] 2021-07-01 16:21
Thanks for your quick reply.

Here is the issue cleaned https://github.com/JulienKode/postcss-8-issue/pull/new/issue/cleaned

**Comment by ai** [comment] 2021-07-01 16:21
I will try to look during next week

**Comment by JulienKode** [comment] 2021-07-01 16:22
Thank you for your help, once you have an idea for it, let me know how I can help regarding this issue

**Comment by JulienKode** [comment] 2021-07-01 16:23
We've try to look at the AST, it seems to have a different behaviour between the version 8.0.9 and 8.1.0, We didn't find why for the moment

**Comment by davidgarry** [comment] 2021-08-08 22:13
Hello @ai 

Did you have time to take a look to this issue ?

**Comment by ai** [comment] 2021-08-08 22:15
Nope. Seems like I will not have time for next week too.

@davidgarry Can I ask you to debug the issue and send PR? Feel free to ask questions.

**Comment by davidgarry** [comment] 2021-08-08 22:37
First of all, thank you to answer each time so quickly 👏 

I will try to allocate some time in my team to investigate more deeper the issue in the coming weeks !

**Comment by TheSeally** [comment] 2021-08-18 23:03
Hello I tried to investigate the problem and I think it is connected with plugin `postcss-prefix-selector` (this plugin was on test case) that is not adopted to `postcss` and `postcss-nested` changes.
The main change is moving `postcss-nested` to visitor API. Wherein plugin `postcss-prefix-selector` depends on result of `postcss-nested` plugin. 
Thus before this change `postcss-nested` plugin processed by `runOnRoot` function before `postcss-prefix-selector` and change result for it. Now `postcss-nested` processed in visitor block (https://github.com/postcss/postcss/blob/0cb9fc2a727f25b543c758d164aa2fa796714604/lib/lazy-result.js#L387-L412)

Because of that in previous implementation `postcss-prefix-selector` get the 2 nodes with following selectors
![image](https://user-images.githubusercontent.com/34841680/129981656-83a67e61-315d-4de4-81ab-ff62a6dd5157.png)
But now it contains only one node with selector `.foo` (because `postcss-nested` was not processed)
![image](https://user-images.githubusercontent.com/34841680/129982029-2c4003b8-7d1a-4ef3-9c03-6c7401551e7b.png)

So I don't know should this fixed in `postcss` or in `postcss-prefix-selector`. Or may be I don't right and my investigation is not correct (if so I can continue my research). 

@ai what do you think?

**Comment by ai** [comment] 2021-08-18 23:06
@TheSeally can we make a dirty refactoring of `postcss-prefix-selector` and move it to `Rule` event to prove this theory?

The file looks very small https://github.com/RadValentin/postcss-prefix-selector/blob/master/index.js

**Comment by TheSeally** [comment] 2021-08-18 23:12
Yeah, I'll try this

**Comment by TheSeally** [comment] 2021-08-18 23:32
I made a dirty change in `postcss-prefix-selector` only for check this theory. After this change the `style.css` file in test case processed normally.
So the changed code:

```javascript
module.exports = function postcssPrefixSelector(options) {
  const prefix = options.prefix;
  const prefixWithSpace = /\s+$/.test(prefix) ? prefix : `${prefix} `;
  const ignoreFiles = options.ignoreFiles ? [].concat(options.ignoreFiles) : [];
  const includeFiles = options.includeFiles
    ? [].concat(options.includeFiles)
    : [];

  return {
    postcssPlugin: 'postcss-prefix-selector',
    Rule(rule) {
      if (
        ignoreFiles.length &&
        rule.source.input.file &&
        isFileInArray(rule.source.input.file, ignoreFiles)
      ) {
        return;
      }
      if (
        includeFiles.length &&
        rule.source.input.file &&
        !isFileInArray(rule.source.input.file, includeFiles)
      ) {
        return;
      }

      const keyframeRules = [
        'keyframes',
        '-webkit-keyframes',
        '-moz-keyframes',
        '-o-keyframes',
      ];

      if (rule.parent && keyframeRules.includes(rule.parent.name)) {
        return;
      }

      rule.selectors = rule.selectors.map((selector) => {
        if (options.exclude && excludeSelector(selector, options.exclude)) {
          return selector;
        }

        if (options.transform) {
          return options.transform(
            prefix,
            selector,
            prefixWithSpace + selector
          );
        }

        return prefixWithSpace + selector;
      });
    }
  }
};
```

**Comment by ai** [comment] 2021-08-18 23:44
Amazing!

Are you came from Cult of Martians? I will mark task as solved my you (you can give me your name in Russian if you want).

Can I ask you to create an issue in `postcss-prefix-selector`. If you will even send PR to it, it will be the best solution.

**Closed by ai** 2021-08-18 23:44 UTC

**Comment by TheSeally** [comment] 2021-08-18 23:46
Yes, I came from Cult of Martians. My name is Виктор.
Ofcourse I will create issue and try to make PR

**Comment by ai** [comment] 2021-08-18 23:50
We mostly put first and last name to task. But if you want I can put only nick.

**Comment by TheSeally** [comment] 2021-08-18 23:51
My full name is Виктор Малий

**Comment by RadValentin** [comment] 2021-08-19 10:30
Version [`1.11.0`](https://github.com/RadValentin/postcss-prefix-selector/releases/tag/v1.11.0) of `postcss-prefix-selector` is out  and includes the fix made by @TheSeally 🚀

**Comment by TheSeally** [comment] 2021-08-19 12:08
@RadValentin thanks for quick response

**Comment by JulienKode** [comment] 2021-09-13 22:08
Well done @TheSeally @ai @RadValentin

**Comment by JulienKode** [comment] 2021-09-13 22:08
Thanks for your help on this
