### ISSUE TITLE
Source map line numbers off by two with no plugins

### ISSUE THREAD

**Issue by alexturpin** [postcss/postcss#926] opened 2016-12-02 16:34 UTC
Hey all,

I've encountered a bit of an issue with sourcemaps. My workflow is that I first compile my SASS code down to CSS, and then use PostCSS on the resulting code / source maps.

My problem is that even with no plugins, after going through PostCSS, source map line numbers are off by 2 (they point to 2 lines before the actual line).

This is the input CSS and input source map generated from SASS:

```css
p{color:red}a{color:green}

/*# sourceMappingURL=before.css.map */
```

```json
{
	"version": 3,
	"file": "styles.css",
	"sources": [
		"styles.scss"
	],
	"sourcesContent": [
		"p {\n\tcolor: red;\n}\n\na {\n\tcolor: green;\n}\n"
	],
	"mappings": "AAAA,AAAA,CAAC,AAAC,CACD,KAAK,CAAE,GAAI,CACX,AAED,AAAA,CAAC,AAAC,CACD,KAAK,CAAE,KAAM,CACb",
	"names": []
}
```

As can be seen on [source-map-visualization](https://sokra.github.io/source-map-visualization/#base64,cHtjb2xvcjpyZWR9YXtjb2xvcjpncmVlbn0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPWJlZm9yZS5jc3MubWFwICov,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3R5bGVzLmNzcyIsInNvdXJjZXMiOlsic3R5bGVzLnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsicCB7XG5cdGNvbG9yOiByZWQ7XG59XG5cbmEge1xuXHRjb2xvcjogZ3JlZW47XG59XG4iXSwibWFwcGluZ3MiOiJBQUFBLEFBQUEsQ0FBQyxBQUFDLENBQ0QsS0FBSyxDQUFFLEdBQUksQ0FDWCxBQUVELEFBQUEsQ0FBQyxBQUFDLENBQ0QsS0FBSyxDQUFFLEtBQU0sQ0FDYiIsIm5hbWVzIjpbXX0=,cCB7Cgljb2xvcjogcmVkOwp9CgphIHsKCWNvbG9yOiBncmVlbjsKfQo=) everything is still linked properly.

Now running them through PostCSS without plugins with this code:

```javascript
var postcss = require('postcss');
var fs = require('fs');
var path = require('path');

var beforeStyles = fs.readFileSync('before.css', 'utf-8');
var beforeMap = fs.readFileSync('before.css.map', 'utf-8');

postcss([])
	.process(beforeStyles, { from: 'before.css', to: 'after.css', map: { inline: false, prev: beforeMap } })
	.then(function(result) {
		fs.writeFileSync('after.css', result.css);
		fs.writeFileSync('after.css.map', result.map);
	}, function(err) {
		console.log(err);
	});
```

Results in the following output:

```css
p{color:red}a{color:green}
/*# sourceMappingURL=after.css.map */
```

```json
{"version":3,"sources":["styles.scss"],"names":[],"mappings":"AAAA,EACC,SAAW,CACX,EAGA,WAAa,CACb","file":"after.css","sourcesContent":["p {\n\tcolor: red;\n}\n\na {\n\tcolor: green;\n}\n"]}
```

Which, we can observe on [source-map-visualization](https://sokra.github.io/source-map-visualization/#base64,cHtjb2xvcjpyZWR9YXtjb2xvcjpncmVlbn0KLyojIHNvdXJjZU1hcHBpbmdVUkw9YWZ0ZXIuY3NzLm1hcCAqLw==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0eWxlcy5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLEVBQ0MsU0FBVyxDQUNYLEVBR0EsV0FBYSxDQUNiIiwiZmlsZSI6ImFmdGVyLmNzcyIsInNvdXJjZXNDb250ZW50IjpbInAge1xuXHRjb2xvcjogcmVkO1xufVxuXG5hIHtcblx0Y29sb3I6IGdyZWVuO1xufVxuIl19,cCB7Cgljb2xvcjogcmVkOwp9CgphIHsKCWNvbG9yOiBncmVlbjsKfQo=), is broken. The `a` selector has no corresponding line number.

**Comment by ai** [comment] 2016-12-02 16:56
Yeap, `a` selector mapping is broken.

Right now I am preparing for conference and will be free after Dec 11. Could it wait until this date? Maybe I will have time on next week.

**Comment by alexturpin** [comment] 2016-12-04 19:02
@ai Yep that's fine, just wanted to make sure that it was logged somewhere.

**Comment by alexturpin** [comment] 2017-01-04 19:06
Hello!

Just wondering if there have been any updates on this? :)

**Comment by ai** [comment] 2017-01-04 19:12
Sorry, I am in other project. Because we had no other reports and problem is not critical this issue is low priority right now.

Do you want to try to fix it by your own? I will help you.

**Comment by alexturpin** [comment] 2017-01-05 00:29
No worries. It's not critical enough for me right now to focus time on fixing it, but if I ever come around to it I'll hit you up to ask for tips on where to look to fix it :)

Thanks

**Comment by GaryJones** [comment] 2017-02-08 11:15
FWIW, I can see evidence of this too.

**Comment by ai** [comment] 2017-02-08 11:18
Be prepare that this issue will not be fixed for few months:

1. I am preparing for React London with talk about Logux.
2. Result is not critical.
3. It doesn’t happen on pure PostCSS stack 😛

**Comment by ai** [comment] 2017-02-08 11:18
I am always open for PR ;)

**Comment by alexturpin** [comment] 2017-02-08 15:20
@ai What do you mean by pure PostCSS stack? Weback plugin?

**Comment by ai** [comment] 2017-02-08 15:22
I mean do all CSS work inside PostCSS: linting, preprocessing, prefixes, postprocessing

**Comment by alexturpin** [comment] 2017-02-08 15:23
Ah so it's a result of incompatibility between other sourcemaps and PostCSS' sourcemap then?

**Comment by ai** [comment] 2017-02-08 15:26
Yeap this issue happen when you have previous source map

**Comment by ai** [comment] 2017-02-08 15:27
Of course, it is a error and I will fix it. PostCSS should update others source map.

**Comment by alexturpin** [comment] 2017-02-08 15:35
No worries! Just trying to understand better :)

**Comment by subicura** [comment] 2017-03-15 23:58
+1

**Comment by ai** [comment] 2017-03-16 00:01
@subicura I will look into it again after React London (March 28)

**Comment by subicura** [comment] 2017-03-16 00:02
@ai Thanks!!

**Comment by ai** [comment] 2017-04-14 01:28
I tried few changes but had no success.

PostCSS source maps are good. Sass source maps are good. Problem comes from mozilla’s `source-map`, when it try to merge source maps.

Since Sass compatibility is not goal for PostCSS, I will close this issue (anyway I don’t know solution right now).

Possible solutions:

* Short-term: use postcss-based preprocessors like PreCSS or cssnext. In this case you will get 100% compatibility with other postcss-based tools like Autoprefixer or Stylelint.
* Long-term: when we move selector and value parser inside core, we will split CSS into smaller chunks. Source maps may be fixed by it. https://github.com/postcss/postcss/issues/754

**Closed by ai** 2017-04-14 01:28 UTC

**Comment by x-yuri** [comment] 2018-01-26 10:56
@ai Could you please help me reproduce the issue without `postcss`?

`1.scss`:
```scss
body {
    background: #ddd;
}
div {
    width: 100px;
    height: 100px;
    margin: auto;
    background: #666;
}
```

```
$ yarn add node-sass postcss-cli
$ rm 1.css*; ./node_modules/.bin/node-sass --output-style compressed --source-map true --source-map-contents 1.scss 1.css
$ rm 2.css*; ./node_modules/.bin/postcss 1.css --output 2.css
```

`node-sass` produces the following mappings:

```
AAAA,AAAA,IAAI,AAAC,CACD,UAAU,CAAE,IAAI,CACnB,AACD,AAAA,GAAG,AAAC,CACA,KAAK,CAAE,KAAK,CACZ,MAAM,CAAE,KAAK,CACb,MAAM,CAAE,IAAI,CACZ,UAAU,CAAE,IAAI,CACnB
```

But after `postcss` I get:

```
AAAA,KACI,eAAgB,CACnB,IAEG,YACA,aACA,YACA,eAAgB,CACnB
```

I want to file a bug to `source-map` package regarding the issue. Or at least try to figure out why the mappings change. So I'd like to have a test case with `source-map` package alone.

**Comment by ai** [comment] 2018-01-26 10:59
What is a problem with this mapping? PostCSS generates less nodes, so result mapping is smaller

**Comment by x-yuri** [comment] 2018-01-26 12:09
Let the author [speak for himself][1]:

> Ruby sass sourcemaps are lacking a lot according to previous discussions with am11. I decided to do better than that and therefore libsass has much more detailed source-maps than ruby sass does (not sure if this is still true, since those discussion are over a year old).

Also, I'm curious what makes `source-map` package change source maps when no code changes.

P.S. I'm going to check if OP's issue still holds.

[1]: https://github.com/sass/node-sass/issues/1206#issuecomment-160246152

**Comment by x-yuri** [comment] 2018-01-26 12:11
By the way, it might be the root cause of [this issue][1].

[1]: https://github.com/mozilla/source-map/issues/252

**Comment by x-yuri** [comment] 2018-01-31 20:37
I now see. Regarding [OP's test case][off-by-two.tar.gz]. IMO nothing is broken in the "after" source map (as well as in the "before" one). [`source-map-vizualization`][1] doesn't have the last word in it. It's just another consumer. Which happens to be a visualization tool, and not the [best][2] [one][3] if you ask me. The whole issue with source maps comes from—correct me if I'm wrong—non-strict spec. `source-map` package doesn't do anything wrong, it just follows another interpretation of the spec. Not that I'm trying to put the blame on the spec, it probably has its reasons.

Then, these days the issue can't be reproduced (line numbers off by two). Or line numbers are simply off by one consistently across the whole stylesheet. At least in Chromium 63.0.3239.132. From what I can see, Chromium takes the [first mapping][4] *after* the opening curly bracket.

[off-by-two.tar.gz]: https://github.com/postcss/postcss/files/1682809/off-by-two.tar.gz

[1]: https://sokra.github.io/source-map-visualization/
[2]: http://libsass.ocbnet.ch/srcmap/
[3]: https://stackoverflow.com/a/40784755/52499

[4]: https://github.com/webpack-contrib/css-loader/issues/381#issuecomment-360687110

Regarding [my test case][less-segments.tar.gz], I was wondering why so much less mappings was left after `postcss`. So, `postcss` parses the css code, which results in AST with line/column numbers. No processing is done. Then [source map][6] is generated based on the AST. After which original source map is [applied][7].

Now then, what does "apply" here mean again? We have source code (`A`), source code `A` after processing with `sass` (`B`), and source code `B` after processing with `postcss` (`C`, nothing has changed). And we have two source maps: `B -> A`, `C -> B`. When applying, `source-map` package takes a mapping from `C -> B` source map, its original position (`B`) and maps it using `B -> A` source map to original original position (`A`). That gives us as many mappings as was generated by `postcss`, but there could be [less][8] (when adjacent mappings point to the same position).


[less-segments.tar.gz]: https://github.com/postcss/postcss/files/1682852/less-segments.tar.gz
[5]: https://github.com/postcss/postcss/blob/6.0.16/lib/lazy-result.es6#L42
[6]: https://github.com/postcss/postcss/blob/6.0.16/lib/lazy-result.es6#L351
[7]: https://github.com/postcss/postcss/blob/6.0.16/lib/map-generator.es6#L107
[8]: https://github.com/mozilla/source-map/blob/0.7.0/lib/source-map-generator.js#L341
