### ISSUE TITLE
Plugin creation, variables type

### ISSUE THREAD

**Issue by loick** [postcss/postcss#801] opened 2016-05-04 10:21 UTC
Hi everyone, I got an issue when I created a postcss plugin with the type of the variables. 

I created a declaration like this `postcss.decl({ prop: 'padding', value: 0 })`, but after compiling with cssnano, I got a weird issue `decl.value.indexOf is not a function`. After testing almost everything, I found out this was due to the type of my value (so here, an integer). 

What do you think about casting the type of the values into a string when we use the postcss.decl ? Maybe this would avoid this kind of situation, and I don't really see any couple property/value where this would be blocker.

**Comment by ben-eb** [comment] 2016-05-04 11:08
Duplicate of https://github.com/postcss/postcss/issues/339.

**Closed by ben-eb** 2016-05-04 11:08 UTC
Labels: duplicate
