### ISSUE TITLE
DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss\package.json.

### ISSUE THREAD

**Issue by LP1994** [postcss/postcss#1455] opened 2020-11-05 03:32 UTC
This is not a error!!!

operating system: Windows 10,
node: 15.1.0,
npm: 6.14.8,
webpack: 5.4.0,
postcss: 8.1.4

This is only a warning issued by "nodejs". It is recommended to make corrections according to the warning, because some writing methods are not recommended.

![image](https://user-images.githubusercontent.com/12012671/98194446-68c21680-1f5a-11eb-8624-2025f06536c6.png)

**Comment by ShenHongFei** [comment] 2020-11-05 08:25
fixed in this PR
https://github.com/postcss/postcss/pull/1456

**Comment by ai** [comment] 2020-11-05 15:51
The fix was released in 8.1.5.

**Comment by ai** [comment] 2020-11-05 16:53
@ShenHongFei just replacing `./` → `./*` cause an issue in Node.js 12.

Can we fix this warning by adding `./` and `./*` together in `package.json→exports`?

**Comment by ShenHongFei** [comment] 2020-11-06 02:39
> @ShenHongFei just replacing `./` → `./*` cause an issue in Node.js 12.
> 
> Can we fix this warning by adding `./` and `./*` together in `package.json→exports`?

Yes, that works.

**Comment by ai** [comment] 2020-11-06 02:51
How I can see this warning?

**Comment by ai** [comment] 2020-11-08 12:08
@LP1994 what do I need to call to see this warning?

**Comment by LP1994** [comment] 2020-11-09 07:05
> @LP1994 what do I need to call to see this warning?

These warnings appear only after upgrading to the following versions:
"postcss": "8.1.6",
"webpack": "5.4.0",
"npm": "6.14.8",
"node": "15.1.0",
operating system: Windows 10

**Comment by ai** [comment] 2020-11-10 15:53
Another way to fix the problem https://github.com/postcss/postcss/commit/92155c73e105a36af5196a75bcc34ada377a711f

**Comment by ai** [comment] 2020-11-10 15:55
Nope, this way again kills Node.js 15 in CommonJS.

Can you create a small test repo?

**Comment by LP1994** [comment] 2020-11-10 15:58
> Nope, this way again kills Node.js 15 in CommonJS.
> 
> Can you create a small test repo?
Later, I'll try.

**Comment by borodadada** [comment] 2020-12-14 08:56
Hello. I have DeprecationWarning

(node:29624) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\js\project\web\node_modules\css-loader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
webpack built bb7b669f975520d3919d in 8025ms
i ｢wdm｣: Hash: bb7b669f975520d3919d
Version: webpack 4.44.2

**Comment by DopamineDriven** [comment] 2020-12-18 21:17
I too have a deprecation warning, using postcss 8.2.1
nodejs 15.4
nextjs v 10.03

```s
$ yarn dev
yarn run v1.22.5
$ next -p 3434
Loaded env from C:\Users\Anthr\drisdell-consulting-services\.env.local
Loaded env from C:\Users\Anthr\drisdell-consulting-services\.env
(node:12964) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Anthr\drisdell-consulting-services\node_modules\next\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on http://localhost:3434
(node:12964) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Anthr\drisdell-consulting-services\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
```

**Comment by ozbigcat** [comment] 2020-12-28 02:01
The current "solution" by changing  `"./": "./"` to `"./*": "./*"` (or adding `"./*": "./*"`)  did remove the warning, but it breaks the program on certain functionality.

However, if I reading this correctly, according to:
https://nodejs.org/api/packages.html#packages_subpath_exports

shouldn't the change be `"./*": "./*.js"` ? 
I have tried it and it works..but of course, need a more thorough test,

Here is a small repository to reproduce the current warning (pending the solution)
https://github.com/ozbigcat/postcss-1455-deprecation-warning

My environment:
Windows 10
Node 15.3.0
npm 7.1.0
autoprefixer 10.1.0
postcss 8.2.1
postcss-cli 8.3.1
tailwindcss 2.0.2

**Comment by ozbigcat** [comment] 2020-12-28 04:34
Uh, just found a case where `"./*": "./*.js"` also did not work.
In this case, it tries to look for a 'package.json.js' which is not valid name... happy to go back to the warning... :-(

**Comment by JR2Media** [comment] 2020-12-29 13:45
Having this problem. Also using tailwind, postcss, autoprefixer and gulp. No idea how to solve it.

Is this an error in one of the packages I'm using? It's only a warning at this point so I'm not terribly concerned but I am confused at the error message.

**Comment by Colorin09** [comment] 2021-01-10 08:43
Hello, I was wondering if someone got a solution for that issue, i am having the same issue and replacing with "./*" only breaks other postcss imports in the lib directory (updating to vers. 8.0.0 did not resolve the issue :/)

**Comment by davidnjohansson** [comment] 2021-01-11 08:55
I'm facing the same warning. I'm on node 15.5.1 with postcss 8.2.4

**Comment by Colorin09** [comment] 2021-01-11 15:56
I managed to fix the problem by downgrading to node.js vers. 14.15.1,
 but couldn't find exactly what was the error, updating autowriter and postcss libraries did not work:/

**Comment by leandroruel** [comment] 2021-01-12 05:41
well, i'm getting this warning too, it's coming from node but it's related to postcss
node 15.
postcss 8.2.2
tailwind 2.0

**Comment by JCGithu** [comment] 2021-01-13 19:57
Getting the same error as those commenting the last few days. 
node 15.
postcss 8.2.2
tailwind 2.0
Windows 10.

**Comment by ai** [comment] 2021-01-13 19:58
We do not need more reproduction cases. We need some solution, which will work on all Node.js. Adding `./*` breaking old Node.js versions.

**Comment by duckness** [comment] 2021-01-14 02:18
Some relevant PRs from node repo:

* https://github.com/nodejs/node/pull/35747
* https://github.com/nodejs/node/pull/36859

**Comment by ai** [comment] 2021-01-14 10:26
Seems like the problem was fixed in Node.js

**Closed by ai** 2021-01-14 10:26 UTC

**Comment by duckness** [comment] 2021-01-15 06:47
Can confirm I'm not running into the issue after updating to `15.6.0`

**Comment by omostan** [comment] 2021-02-05 11:33
upgrading nodejs to v15.8.0 fixed the warnings for me

**Comment by www-chique** [comment] 2021-02-19 15:22
> 
> 
> upgrading nodejs to v15.8.0 fixed the warnings for me

Indeed it's gone when I updated Node to 15.9.0

**Comment by EricWVGG** [comment] 2021-04-20 19:32
I did not have v15.11.0, but it has now surfaced in v16.0.0

**Comment by logemann** [comment] 2021-04-22 14:28
Cause of v16 being broken. We can re-open this one right? Even though its not a postcss issue !?

**Comment by ai** [comment] 2021-04-22 14:31
https://github.com/postcss/postcss/issues/1561

**Comment by howsen82** [comment] 2021-04-24 01:57
Same issues happen on nodejs v16.0.0

**Comment by ai** [comment] 2021-04-24 01:58
Fixed in the latest PostCSS

**Comment by Jesse-Box** [comment] 2021-04-28 20:25
I'm running node 16 and updating PostCSS to version 8.2.1(latest at the time) fixed the issue for me.

**Comment by logemann** [comment] 2021-04-28 22:30
@ai upgraded postcss to 8.2.13 without any difference regarding the error.

**Comment by ai** [comment] 2021-04-28 22:38
@logemann checkout nested versions `npm ls | grep postcss`

**Comment by logemann** [comment] 2021-04-29 08:08
▶ npm ls | grep postcss
├── gatsby-plugin-postcss@4.3.0
├── postcss@8.2.13

**Comment by danicunhac** [comment] 2021-05-06 12:45
If you're having this error, simply downgrade your node version to LTS if you're above it.

**Comment by k4y4k** [comment] 2021-05-23 02:01
Yeah, hi :wave: 

Downgrading to LTS is not possible for me and I believe this issue is short-circuiting image loading in my Gatsby site (private project, can't share the repo, sorry). Are there any steps I could take to troubleshoot the issue?

**Comment by ai** [comment] 2021-05-23 02:16
@k4y4k

1. Update to the next LTS, 14.x or 16.x
2. Update to Node.js 13.13 or bigger (not recommended)

**Comment by k4y4k** [comment] 2021-05-23 02:21
```
$ node --version
v16.2.0
``` 

Is 16 LTS? nodejs.org says `16.x` is Current

**Comment by ai** [comment] 2021-05-23 02:23
@k4y4k update PostCSS to the latest version. We fixed this bug in Node.js 16

**Comment by ignat** [comment] 2021-06-17 10:30
I see this warning with:

- node 16.3.0
- postcss 8.3.5

**Comment by youssef-aitali** [comment] 2021-07-01 13:18
> @k4y4k update PostCSS to the latest version. We fixed this bug in Node.js 16

this worked for me!

**Comment by vitoneto** [comment] 2021-09-03 14:39
This was happening to me!
I was using node v16 i just change to node v14 and the error message stoped and the compilation works very well.

**Comment by armordog** [comment] 2021-10-21 17:56
This seems to be back for node 17.x.
Building on Vercel
node 17.0.1
postcss 8.3.10

> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in C:\gitl\web-apps
\node_modules\next\node_modules\postcss\package.json

I assume this is the same problem because under node 16.x I see the deprecation error at the same place.

**Comment by ai** [comment] 2021-11-23 15:39
@ramdaniAli yeap, check you lock file. Today `postcss` can be found in nested dependencies of most of front-end projects.

For instance, `css-loader` uses PostCSS.

**Comment by ramdaniAli** [comment] 2021-11-23 15:54
@ai  looks like my project is using this version of postcss "^7.0.32" . 
normally i can't just do npm install postCSS, so how can I safely  update it ?

**Comment by ai** [comment] 2021-11-23 15:55
There is no way to do it in CRA. You should do `eject` and avoid using CRA in the future since this project is abandoned.

**Comment by ramdaniAli** [comment] 2021-11-23 16:03
create react app is still maintained by facebook (meta) , but they have like 1k issues ,
Btw  , there is no one who has already used create react app and fixed this problem  ?

**Comment by ai** [comment] 2021-11-23 16:23
> create react app is still maintained by facebook (meta) , but they have like 1k issues ,

They can’t update PostCSS from 7 to 8 for year. It is only big framework, which didn’t update it.

Just look lack of response and solutions in their issues about PostCSS 8.

**Comment by ramdaniAli** [comment] 2021-11-23 18:03
ok, I see, in any case, thank you for the quick answers @ai  . 

last thing, dou you have any idea which package uses postCSS ? or some tips on how I can detect it ? 

Im working on a project with theses packages : 

```
  "dependencies": {
    "@date-io/date-fns": "^2.11.0",
    "@date-io/moment": "^2.11.0",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/icons-material": "^5.0.0",
    "@mui/lab": "^5.0.0-alpha.52",
    "@mui/material": "^5.0.0",
    "@mui/styled-engine-sc": "^5.0.0",
    "@mui/styles": "^5.0.1",
    "@mui/x-data-grid": "^5.0.0-beta.7",
    "@react-spring/parallax": "^9.3.0",
    "@react-spring/web": "^9.3.0",
    "@reduxjs/toolkit": "^1.6.1",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "aos": "^2.3.4",
    "apexcharts": "^3.28.3",
    "axios": "^0.22.0",
    "date-fns": "^2.25.0",
    "formik": "^2.2.9",
    "framer-motion": "^4.1.17",
    "material-ui-image": "^3.3.2",
    "moment": "^2.29.1",
    "notistack": "^2.0.2",
    "react": "^17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.17.0",
    "react-icons": "^4.3.1",
    "react-lazy-load-image-component": "^1.5.1",
    "react-loader-spinner": "^4.0.0",
    "react-parallax": "^3.3.0",
    "react-redux": "^7.2.5",
    "react-reveal": "^1.2.2",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "react-spring": "^9.3.0",
    "react-useanimations": "^2.0.6",
    "redux": "^4.1.1",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.3.0",
    "redux-watch": "^1.2.0",
    "styled-components": "^5.3.1",
    "stylis": "^4.0.10",
    "stylis-plugin-rtl": "^2.1.1",
    "swiper": "^7.0.8",
    "web-vitals": "^0.2.4",
    "workbox-background-sync": "^5.1.3",
    "workbox-broadcast-update": "^5.1.3",
    "workbox-cacheable-response": "^5.1.3",
    "workbox-core": "^5.1.3",
    "workbox-expiration": "^5.1.3",
    "workbox-google-analytics": "^5.1.3",
    "workbox-navigation-preload": "^5.1.3",
    "workbox-precaching": "^5.1.3",
    "workbox-range-requests": "^5.1.3",
    "workbox-routing": "^5.1.3",
    "workbox-strategies": "^5.1.3",
    "workbox-streams": "^5.1.3",
    "yup": "^0.32.9"
  },
```

```
 "devDependencies": {
    "babel-plugin-import": "^1.13.3",
    "customize-cra": "^1.0.0",
    "react-app-rewired": "^2.1.8",
    "snyk": "^1.769.0"
  }
```

**Comment by ramdaniAli** [comment] 2021-11-23 18:14
looks like the issue is  from react-scripts  😭 

here is the full report : 

![image](https://user-images.githubusercontent.com/33391424/143080925-fa66a92a-d446-40b2-b4b8-ed447317ed40.png)

**Comment by k4y4k** [comment] 2021-11-23 21:00
@ramdaniAli `yarn why` will tell you why you have a package. e.g. `yarn why react`

**Comment by sostenesapollo** [comment] 2021-11-23 21:31
stills in `node v16.13.0`

**Comment by ramdaniAli** [comment] 2021-11-25 03:33
> @ramdaniAli `yarn why` will tell you why you have a package. e.g. `yarn why react`

@k4y4k thank you for the tip but unfortunately, it doesn't help, because postcss is  a sub-dependency , so it's not in my package.json but on my yarn.lock file 

@sostenesapollo  Yes Im on `node v16.13.0`  , if I downgrade the version I would no longer have the error? afterwards, that doesn't necessarily solve the problem but Its good for me xD , so any idea which is the most recent version of node where we do not have this problem ?

**Comment by k4y4k** [comment] 2021-11-25 03:34
@ramdaniAli yeah. I know. that's how you find why things are installed if you didn't ask for them. That's why I gave you that tip, so you could find 'why'.

**Comment by luk3skyw4lker** [comment] 2021-12-30 19:58
it's still happening in node version 16.13.1

**Comment by padmini2000** [comment] 2022-04-30 07:44
failed to compile in my react app

**Comment by kenatjh** [comment] 2023-06-22 13:08
this is open source

**Comment by arprinceofficial** [comment] 2024-01-26 19:41
(node:6112) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\Github Projects\emasbd\emasbd_frontend\node_modules\flowbite-vue\package.json imported from D:\Github Projects\emasbd\emasbd_frontend\node_modules. Mapping specifiers ending in "/" is no longer supported.
(Use node --trace-deprecation ... to show where the warning was created)

(node:6112) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving "./dist//index.mjs" for module request ".//index.mjs" matched to "./*" in the "exports" field module resolution of the package at D:\Github Projects\emasbd\emasbd_frontend\node_modules\flowbite-vue\package.json imported from D:\Github Projects\emasbd\emasbd_frontend\node_modules.

pls help me for getting this warning
