### ISSUE TITLE
CssSyntaxError on sourcemap

### ISSUE THREAD

**Issue by TannerS** [postcss/postcss#1602] opened 2021-06-15 00:41 UTC
Hello, I am very new to all this and still learning but our team project from switching from `node-sass-chokidar` to `node-sass`, we generate our styles, and after we run postcss using the autoprefix. Since this siwtch (and i'm not sure which change is too blame) we been getting this issue and I am not familiar enough with this to figure out how to fix it. Any help is appreciated and sorry for any naiveness on my end.

![image](https://user-images.githubusercontent.com/8866319/121975971-79383c00-cd48-11eb-8867-fe1f81be8057.png)

**Comment by ai** [comment] 2021-06-15 02:16
Try to replace `public/css` to `public/CSS/**/*.css`.

Seems like you send the whole files from directory to PostCSS, but PostCSS supports only CSS file.

**Comment by TannerS** [comment] 2021-06-15 16:47
hey! i was able to fix this issue but not sure how, how ever I ran into
another issue, the output files for the postcss files are not being placed
into the same file structure as they were imputed

so /public/css subdirectories are all being placed in a single folder in
the output, not within the same subdirectores, any ideas?

**Comment by ai** [comment] 2021-06-15 16:49
@TannerS sorry, I will close this issue since it is not a bug.

I can’t help you with this, since it is not really `postcss` specific. It is a general question about file processing.

**Closed by ai** 2021-06-15 16:49 UTC
