### ISSUE TITLE
Stop using fixed version of dependencies

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#312] opened 2015-04-27 04:27 UTC
I know you have some reasons.

But we should more trust semver (just a bit) and take some times to teach people their mistake when they did some, instead of private users about bugfixes ?

At least if (you don't want to use `^` range), we might use `>=X.Y <X.Y+1` (that allow bugfixes)?

I know the kind of story you are going to tell me: some people publish minor bump that break things. You did in the past. I did too. It happen. But as open source contributors, we should promote semver and show people how to do each times some issues came up, instead of being afraid and use fixed versions.

**Comment by ai** [comment] 2015-04-27 09:53
I use fixed version only for `devDependencies`. What benefits we will take from flexble versions?

**Comment by MoOx** [comment] 2015-04-27 10:14
Get patchs ?
And for dependencies, you don't use caret range, which is the recommanded method by npm (works great with semver).

**Comment by ai** [comment] 2015-04-27 10:16
You suggest to replace `~` to `^` in `dependencies`? Yeap, we can do it.

**Comment by MoOx** [comment] 2015-04-27 10:22
+ for dev deps too.

Btw, instead of having to update all dev deps at the same time by hand, with potential bugs from everywhere (at the same time), you might just want to use `^` too in order to discover potential bugs (due to some module not respecting semver) from time to time.

**Comment by ai** [comment] 2015-04-27 10:30
Manual update is better for three reason:

* I have 15 free minutes and fix some small issue. Then I push changes to GitHub and Travis CI load new version of some development library. It broke tests. But I have no time to fix them.
* Some developers can report a issue because of old libbraries in their `node_modules`.
* Some libraries are using in benchmark, so regression will not be tested on Travis CI. We can add benchmark to Travis CI, of course. But it will dramatically slow down CI.

**Comment by ai** [comment] 2015-04-27 22:21
Hm. I found a problem with `^` in Autoprefixer. For example, Browserslist update from 0.2 to 0.3 brings new features. So Autoprefixer public API will be changed for this new features.

**Comment by MoOx** [comment] 2015-04-28 04:31
Nope. ^0.2 will not install 0.3 since 0.x are considered by semver as totally unstable API (that's why I try to never publish 0.x btw ^^)
See doc for caret range https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4

**Comment by tunnckoCore** [comment] 2015-04-28 07:51
You just follow https://github.com/jonathanong/ferver its pretty simple - "versioning for those of us who only care about breaking changes"

| Number        | semver                  | ferver                  |
|---------------|-------------------------|-------------------------|
| Major         | Breaking changes        | Major breaking changes  |
| Minor         | New features            | Minor breaking changes  |
| Patch         | Non-breaking bug fixes  | Non-breaking changes    |

i'm trying to follow it whenever possible.

**Comment by MoOx** [comment] 2015-04-28 08:52
ferver is a sweet idea but as said in the readme, you should not use it https://github.com/jonathanong/ferver/issues/5

**Comment by ai** [comment] 2015-04-28 11:52
@MoOx but what if Browserslist will have 1.1 to 1.2 update in some feature and brings new features to Autoprefixer?

**Comment by MoOx** [comment] 2015-04-28 11:54
That's the idea ! Non breaking added features are automatically downloaded :)
How cool is that ?
That's the power of semver !
Breaking change : major bump (need update by hand)
minor non breaking change (new feature): minor bump (^caret can handle it)
patch: you already know :)

**Comment by ai** [comment] 2015-04-28 11:58
But any new feature in public API must be marked as minor update. Problem is some of npm packages are a part of Autoprefixer public API.

We can use `^` for libraries, that is not a part of public API. Like `base64`.

**Comment by ben-eb** [comment] 2015-06-21 18:41
What I've been doing in cssnano is to update the current release notes whenever a child module adds functionality. So if cssnano is at `1.4.3` and I add some update to one of its children which improves compression, in that module it will be marked as a feature or bug fix accordingly, and then as cssnano would get that functionality 'for free' with semver, there's no need to push a new minor/patch version.

So I am pro-semver in this regard, it is a lot less manual than locking dependency versions and allows you to get on with more important things. :smile:

**Comment by ai** [comment] 2015-08-03 23:11
Done d97cbe5

**Closed by ai** 2015-08-03 23:11 UTC
Labels: 5.0, enhancement
