### ISSUE TITLE
Plugin initializer called twice

### ISSUE THREAD

**Issue by pascalduez** [postcss/postcss#529] opened 2015-08-28 09:19 UTC
A plugin that leverage options as argument makes the plugin initializer function to run twice.

Not sure whether this is intended?

```js
import postcss from 'postcss';

export default postcss.plugin('postcss-test', opts => {
  console.log('test');

  return css => { /* noop */ };
});
```
```js
let css = postcss(plugin(opts)).process(input).css;
```
Logs:
```
test
test
```

```js
let css = postcss(plugin).process(input).css;
```
Logs:
```
test
```

Which means at the moment it hazardous to run code outside of the closure.

**Comment by ben-eb** [comment] 2015-08-28 09:22
Duplicate of https://github.com/postcss/postcss/issues/415.

**Closed by ben-eb** 2015-08-28 09:22 UTC
Labels: duplicate

**Comment by pascalduez** [comment] 2015-08-28 09:25
Woops, sorry :blush:
