### ISSUE TITLE
`raws` data is ignored when cloning a declaration

### ISSUE THREAD

**Issue by HaoyCn** [postcss/postcss#843] opened 2016-07-12 07:15 UTC
as the following code shows, the IE hack symbol `_` is not copied when method `clone` is invoked.

```
var postcss = require('postcss');
var decl = postcss.parse('div { _height: 10px }').first.first;
console.log(decl.raws.before, decl.clone().raws.before);// _ , undefined 
```

**Comment by ben-eb** [comment] 2016-07-12 10:15
Duplicate of https://github.com/postcss/postcss/issues/364.

**Closed by ben-eb** 2016-07-12 10:15 UTC
