### ISSUE TITLE
Postcss 7.0.33 fails with exception using pre-postcss 8 plugins

### ISSUE THREAD

**Issue by heath-freenome** [postcss/postcss#1413] opened 2020-09-17 01:34 UTC
With the following postcss dependencies in my `package.json` file, when I upgraded to `postcss@7.0.33`

    "postcss-apply": "^0.12.0",
    "postcss-cli": "^7.1.2",
    "postcss-extend": "^1.0.5",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-nested": "^4.2.3",
    "postcss-preset-env": "^6.7.0",
    "postcss-reporter": "^6.0.1",
    "postcss-scss": "^2.1.1",

I get the following error when I do a simple `npm ci`:
```
TypeError: Class constructor Parser cannot be invoked without 'new'
    at new ScssParser (./node_modules/postcss-scss/lib/scss-parser.js:19:20)
    at scssParse (./node_modules/postcss-scss/lib/scss-parse.js:9:16)
    at new LazyResult (./node_modules/postcss/lib/lazy-result.js:54:16)
    at Processor.process (./node_modules/postcss/lib/processor.js:116:12)
    at ./node_modules/postcss-cli/index.js:217:10
    at async Promise.all (index 0)
```

According to the release notes this new error is supposed to detect postcss 8 plugins.  Yet all of the ones I am using, I've been using for a while with `postcss@7.0.32`

**Comment by erikig** [comment] 2020-09-17 01:40
This appears to be a duplicate of the previous issue - https://github.com/postcss/postcss/issues/1412 #1412

**Comment by heath-freenome** [comment] 2020-09-17 01:47
Here's the results for the  request from the other issue:
```
npm ls | grep postcss                                             
│ │ │ ├── postcss@7.0.33 deduped
│ │ │ └── postcss-value-parser@4.0.3
│ │ │ │ └── postcss@7.0.33 deduped
│ │ │ ├── postcss@7.0.33 deduped
│ │ │ ├─┬ postcss-modules-extract-imports@2.0.0
│ │ │ │ └── postcss@7.0.33 deduped
│ │ │ ├─┬ postcss-modules-local-by-default@3.0.2
│ │ │ │ ├── postcss@7.0.33 deduped
│ │ │ │ ├── postcss-selector-parser@6.0.2 deduped
│ │ │ │ └── postcss-value-parser@4.1.0
│ │ │ ├─┬ postcss-modules-scope@2.2.0
│ │ │ │ ├── postcss@7.0.33 deduped
│ │ │ │ └── postcss-selector-parser@6.0.2 deduped
│ │ │ ├─┬ postcss-modules-values@3.0.0
│ │ │ │ └── postcss@7.0.33 deduped
│ │ │ ├── postcss-value-parser@4.1.0
│ │ ├─┬ postcss-flexbugs-fixes@4.2.1
│ │ │ └── postcss@7.0.33 deduped
│ │ ├─┬ postcss-loader@3.0.0
│ │ │ ├── postcss@7.0.33 deduped
│ │ │ ├── postcss-load-config@2.1.0 deduped
├─┬ postcss@7.0.33
├─┬ postcss-apply@0.12.0
│ └── postcss@7.0.33 deduped
├─┬ postcss-camelcaser@0.2.0
│ └─┬ postcss@5.2.18
├─┬ postcss-cli@7.1.2
│ ├── postcss@7.0.33 deduped
│ ├─┬ postcss-load-config@2.1.0
│ ├── postcss-reporter@6.0.1 deduped
├─┬ postcss-extend@1.0.5
│ └─┬ postcss@5.2.18
├─┬ postcss-import@12.0.1
│ ├── postcss@7.0.33 deduped
│ ├── postcss-value-parser@3.3.1
├─┬ postcss-loader@3.0.0
│ ├── postcss@7.0.33 deduped
│ ├── postcss-load-config@2.1.0 deduped
├─┬ postcss-nested@4.2.3
│ ├── postcss@7.0.33 deduped
│ └─┬ postcss-selector-parser@6.0.2
├─┬ postcss-preset-env@6.7.0
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-value-parser@4.0.2
│ │ └── postcss@7.0.33 deduped
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-selector-parser@5.0.0
│ │ └── postcss@7.0.33 deduped
│ ├── postcss@7.0.33 deduped
│ ├─┬ postcss-attribute-case-insensitive@4.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-selector-parser@5.0.0
│ ├─┬ postcss-color-functional-notation@2.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-color-gray@5.0.0
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-color-hex-alpha@5.0.3
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-values-parser@2.0.1 deduped
│ ├─┬ postcss-color-mod-function@3.0.3
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-color-rebeccapurple@4.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-values-parser@2.0.1 deduped
│ ├─┬ postcss-custom-media@7.0.8
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-custom-properties@8.0.11
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-values-parser@2.0.1 deduped
│ ├─┬ postcss-custom-selectors@5.1.2
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-selector-parser@5.0.0 deduped
│ ├─┬ postcss-dir-pseudo-class@5.0.0
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-selector-parser@5.0.0
│ ├─┬ postcss-double-position-gradients@1.0.0
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-env-function@2.0.2
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-focus-visible@4.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-focus-within@3.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-font-variant@4.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-gap-properties@2.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-image-set-function@3.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-initial@3.0.2
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-lab-function@2.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-logical@3.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-media-minmax@4.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-nesting@7.0.1
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-overflow-shorthand@2.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-page-break@2.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-place@4.0.1
│ │ ├── postcss@7.0.33 deduped
│ │ └─┬ postcss-values-parser@2.0.1
│ ├─┬ postcss-pseudo-class-any-link@6.0.0
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-selector-parser@5.0.0 deduped
│ ├─┬ postcss-replace-overflow-wrap@3.0.0
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-selector-matches@4.0.0
│ │ └── postcss@7.0.33 deduped
│ └─┬ postcss-selector-not@4.0.0
│   └── postcss@7.0.33 deduped
├─┬ postcss-reporter@6.0.1
│ └── postcss@7.0.33 deduped
├─┬ postcss-scss@2.1.1
│ └── postcss@7.0.33 deduped
│ │ └── postcss-value-parser@4.1.0
│ ├─┬ @stylelint/postcss-css-in-js@0.37.2
│ ├─┬ @stylelint/postcss-markdown@0.36.1
│ │ ├── postcss@7.0.33 deduped
│ │ └── postcss-value-parser@4.1.0 deduped
│ ├── postcss@7.0.33 deduped
│ ├─┬ postcss-html@0.36.0
│ ├─┬ postcss-less@3.1.4
│ │ └── postcss@7.0.33 deduped
│ ├── postcss-media-query-parser@0.2.3
│ ├── postcss-resolve-nested-selector@0.1.1
│ ├─┬ postcss-safe-parser@4.0.2
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-sass@0.4.4
│ │ └── postcss@7.0.33 deduped
│ ├─┬ postcss-scss@2.1.1
│ │ └── postcss@7.0.33 deduped
│ ├── postcss-selector-parser@6.0.2 deduped
│ ├── postcss-syntax@0.36.2
│ ├── postcss-value-parser@4.1.0
│ │ └── postcss@7.0.33 deduped
│ └── postcss@7.0.33 deduped
```

**Comment by ai** [comment] 2020-09-17 01:51
Fixed 2293982

It happens because `postcss-scss` was compiled for ES5-classes and `posctss` 7.0.33 uses ES6-classes

**Comment by heath-freenome** [comment] 2020-09-17 01:53
So there will be a `postcss@7.0.34` available soon?

**Comment by ai** [comment] 2020-09-17 01:56
The fix was released in PostCSS 7.0.34

**Closed by ai** 2020-09-17 01:56 UTC

**Comment by heath-freenome** [comment] 2020-09-17 17:06
cool!

**Comment by rexagod** [comment] 2021-06-15 15:58
Seems to occur in `8.2.10` as well.

```
TypeError: Class constructor Parser cannot be invoked without 'new'
    at new ScssParser (/home/rexagod/repositories/console/frontend/node_modules/postcss-scss/lib/scss-parser.js:19:20)
    at Proxy.scssParse (/home/rexagod/repositories/console/frontend/node_modules/postcss-scss/lib/scss-parse.js:9:16)
    at parser (/home/rexagod/repositories/console/frontend/node_modules/postcss-syntax/parser.js:10:22)
    at Object.parse (/home/rexagod/repositories/console/frontend/node_modules/postcss-syntax/parse.js:28:10)
    at new LazyResult (/home/rexagod/repositories/console/frontend/node_modules/postcss/lib/lazy-result.js:133:16)
    at /home/rexagod/repositories/console/frontend/node_modules/stylelint/lib/getPostcssResult.js:99:19
    at async Promise.all (index 0)
```

**Comment by kaseopea** [comment] 2021-08-16 15:43
Same for `8.3.5`
